class ReportCardInside2Model {
  final String? addDaycare;
  final int? studentId;
  final String? registrationNo;
  final String? admissionNo;
  final String? session;
  final String? studentName;
  final String? sex;
  final String? placeofBirth;
  final String? dob;
  final String? age;
  final int? classId;
  final int? sectionId;
  final String? religion;
  final String? nationality;
  final String? motherTongue;
  final String? qnid;
  final String? hostel;
  final String? aAdharNo;
  final String? emisno;
  final String? parentStatus;
  final String? parentId;
  final String? fatherName;
  final String? fage;
  final String? feducation;
  final String? foccupation;
  final String? fdesignation;
  final String? forganisation;
  final String? faddressRes;
  final String? faddressPerm;
  final String? faddressOffice;
  final String? fphoneOffice;
  final String? fmobileno;
  final String? femail;
  final String? motherName;
  final String? mage;
  final String? meducation;
  final String? moccupation;
  final String? mdesignation;
  final String? morganisation;
  final String? maddressRes;
  final String? maddressPerm;
  final String? maddressOffice;
  final String? mphoneoffice;
  final String? mmobileno;
  final String? memail;
  final String? smsFather;
  final String? smsMother;
  final String? bloodGroup;
  final String? identificationMark;
  final String? height;
  final String? weight;
  final String? asthma;
  final String? epilepsy;
  final String? anyOther;
  final String? bcg;
  final String? hib;
  final String? dpt;
  final String? influenza;
  final String? mmr;
  final String? typhoid;
  final String? polio;
  final String? measles;
  final String? hepatitisA;
  final String? hepatitisB;
  final String? chickenpox;
  final String? dtap;
  final String? anyMedicine;
  final String? anyFood;
  final String? anythingElse;
  final String? spectacles;
  final String? blindness;
  final String? transportUser;
  final String? routeNo;
  final String? routeNameId;
  final String? routePointId;
  final String? midDayTo;
  final String? midDayFrom;
  final String? studentPic;
  final String? fatherPic;
  final String? motherPic;
  final String? aadharPic;
  final String? birthCertificatePic;
  final String? action;
  final String? createDate;
  final String? promotionDate;
  final String? promotionStatus;
  final String? createBy;
  final String? updateBy;
  final String? ppassword;
  final String? rollNo;
  final String? schoolId;
  final String? dateOfAdmission;
  final String? fqualification;
  final String? mqualification;
  final String? whatsAppNo;
  final String? guardianName;
  final String? guardianPhone;
  final String? cityId;
  final String? id;
  final String? pinCode;
  final String? languageId;
  final String? activityId;
  final String? serviceId;
  final String? casteId;
  final String? community;
  final String? coachingId;
  final String? sqnid;
  final String? cityName;
  final String? cityState;
  final String? groupId;
  final String? language;
  final String? houseId;
  final String? tcstatus;
  final String? tcnumber;
  final String? staffFirstChild;
  final String? sibling;
  final String? siblingDetails;
  final String? language1;
  final String? neetiitca;
  final String? caste;
  final String? studentRegNo;
  final String? lastResult;
  final String? tcupload;
  final String? emergencyNo;
  final String? guardianImage;
  final String? shortBio;
  final String? uploadStudentImage;
  final bool? isDaycare;
  final String? toTime;
  final String? fromTime;
  final String? pickupPoint;
  final String? transportType;

  ReportCardInside2Model({
    this.addDaycare,
    this.studentId,
    this.registrationNo,
    this.admissionNo,
    this.session,
    this.studentName,
    this.sex,
    this.placeofBirth,
    this.dob,
    this.age,
    this.classId,
    this.sectionId,
    this.religion,
    this.nationality,
    this.motherTongue,
    this.qnid,
    this.hostel,
    this.aAdharNo,
    this.emisno,
    this.parentStatus,
    this.parentId,
    this.fatherName,
    this.fage,
    this.feducation,
    this.foccupation,
    this.fdesignation,
    this.forganisation,
    this.faddressRes,
    this.faddressPerm,
    this.faddressOffice,
    this.fphoneOffice,
    this.fmobileno,
    this.femail,
    this.motherName,
    this.mage,
    this.meducation,
    this.moccupation,
    this.mdesignation,
    this.morganisation,
    this.maddressRes,
    this.maddressPerm,
    this.maddressOffice,
    this.mphoneoffice,
    this.mmobileno,
    this.memail,
    this.smsFather,
    this.smsMother,
    this.bloodGroup,
    this.identificationMark,
    this.height,
    this.weight,
    this.asthma,
    this.epilepsy,
    this.anyOther,
    this.bcg,
    this.hib,
    this.dpt,
    this.influenza,
    this.mmr,
    this.typhoid,
    this.polio,
    this.measles,
    this.hepatitisA,
    this.hepatitisB,
    this.chickenpox,
    this.dtap,
    this.anyMedicine,
    this.anyFood,
    this.anythingElse,
    this.spectacles,
    this.blindness,
    this.transportUser,
    this.routeNo,
    this.routeNameId,
    this.routePointId,
    this.midDayTo,
    this.midDayFrom,
    this.studentPic,
    this.fatherPic,
    this.motherPic,
    this.aadharPic,
    this.birthCertificatePic,
    this.action,
    this.createDate,
    this.promotionDate,
    this.promotionStatus,
    this.createBy,
    this.updateBy,
    this.ppassword,
    this.rollNo,
    this.schoolId,
    this.dateOfAdmission,
    this.fqualification,
    this.mqualification,
    this.whatsAppNo,
    this.guardianName,
    this.guardianPhone,
    this.cityId,
    this.id,
    this.pinCode,
    this.languageId,
    this.activityId,
    this.serviceId,
    this.casteId,
    this.community,
    this.coachingId,
    this.sqnid,
    this.cityName,
    this.cityState,
    this.groupId,
    this.language,
    this.houseId,
    this.tcstatus,
    this.tcnumber,
    this.staffFirstChild,
    this.sibling,
    this.siblingDetails,
    this.language1,
    this.neetiitca,
    this.caste,
    this.studentRegNo,
    this.lastResult,
    this.tcupload,
    this.emergencyNo,
    this.guardianImage,
    this.shortBio,
    this.uploadStudentImage,
    this.isDaycare,
    this.toTime,
    this.fromTime,
    this.pickupPoint,
    this.transportType,
  });

  factory ReportCardInside2Model.fromJson(Map<String, dynamic> json) {
    return ReportCardInside2Model(
      addDaycare: json['addDaycare'] as String?,
      studentId: json['studentId'] as int?,
      registrationNo: json['registrationNo'] as String?,
      admissionNo: json['admissionNo'] as String?,
      session: json['session'] as String?,
      studentName: json['studentName'] as String?,
      sex: json['sex'] as String?,
      placeofBirth: json['placeofBirth'] as String?,
      dob: json['dob'] as String?,
      age: json['age'] as String?,
      classId: json['classId'] as int?,
      sectionId: json['sectionId'] as int?,
      religion: json['religion'] as String?,
      nationality: json['nationality'] as String?,
      motherTongue: json['motherTongue'] as String?,
      qnid: json['qnid'] as String?,
      hostel: json['hostel'] as String?,
      aAdharNo: json['aAdharNo'] as String?,
      emisno: json['emisno'] as String?,
      parentStatus: json['parentStatus'] as String?,
      parentId: json['parentId'] as String?,
      fatherName: json['fatherName'] as String?,
      fage: json['fage'] as String?,
      feducation: json['feducation'] as String?,
      foccupation: json['foccupation'] as String?,
      fdesignation: json['fdesignation'] as String?,
      forganisation: json['forganisation'] as String?,
      faddressRes: json['faddressRes'] as String?,
      faddressPerm: json['faddressPerm'] as String?,
      faddressOffice: json['faddressOffice'] as String?,
      fphoneOffice: json['fphoneOffice'] as String?,
      fmobileno: json['fmobileno'] as String?,
      femail: json['femail'] as String?,
      motherName: json['motherName'] as String?,
      mage: json['mage'] as String?,
      meducation: json['meducation'] as String?,
      moccupation: json['moccupation'] as String?,
      mdesignation: json['mdesignation'] as String?,
      morganisation: json['morganisation'] as String?,
      maddressRes: json['maddressRes'] as String?,
      maddressPerm: json['maddressPerm'] as String?,
      maddressOffice: json['maddressOffice'] as String?,
      mphoneoffice: json['mphoneoffice'] as String?,
      mmobileno: json['mmobileno'] as String?,
      memail: json['memail'] as String?,
      smsFather: json['smsFather'] as String?,
      smsMother: json['smsMother'] as String?,
      bloodGroup: json['bloodGroup'] as String?,
      identificationMark: json['identificationMark'] as String?,
      height: json['height'] as String?,
      weight: json['weight'] as String?,
      asthma: json['asthma'] as String?,
      epilepsy: json['epilepsy'] as String?,
      anyOther: json['anyOther'] as String?,
      bcg: json['bcg'] as String?,
      hib: json['hib'] as String?,
      dpt: json['dpt'] as String?,
      influenza: json['influenza'] as String?,
      mmr: json['mmr'] as String?,
      typhoid: json['typhoid'] as String?,
      polio: json['polio'] as String?,
      measles: json['measles'] as String?,
      hepatitisA: json['hepatitisA'] as String?,
      hepatitisB: json['hepatitisB'] as String?,
      chickenpox: json['chickenpox'] as String?,
      dtap: json['dtap'] as String?,
      anyMedicine: json['anyMedicine'] as String?,
      anyFood: json['anyFood'] as String?,
      anythingElse: json['anythingElse'] as String?,
      spectacles: json['spectacles'] as String?,
      blindness: json['blindness'] as String?,
      transportUser: json['transportUser'] as String?,
      routeNo: json['routeNo'] as String?,
      routeNameId: json['routeNameId'] as String?,
      routePointId: json['routePointId'] as String?,
      midDayTo: json['midDayTo'] as String?,
      midDayFrom: json['midDayFrom'] as String?,
      studentPic: json['studentPic'] as String?,
      fatherPic: json['fatherPic'] as String?,
      motherPic: json['motherPic'] as String?,
      aadharPic: json['aadharPic'] as String?,
      birthCertificatePic: json['birthCertificatePic'] as String?,
      action: json['action'] as String?,
      createDate: json['createDate'] as String?,
      promotionDate: json['promotionDate'] as String?,
      promotionStatus: json['promotionStatus'] as String?,
      createBy: json['createBy'] as String?,
      updateBy: json['updateBy'] as String?,
      ppassword: json['ppassword'] as String?,
      rollNo: json['rollNo'] as String?,
      schoolId: json['schoolId'] as String?,
      dateOfAdmission: json['dateOfAdmission'] as String?,
      fqualification: json['fqualification'] as String?,
      mqualification: json['mqualification'] as String?,
      whatsAppNo: json['whatsAppNo'] as String?,
      guardianName: json['guardianName'] as String?,
      guardianPhone: json['guardianPhone'] as String?,
      cityId: json['cityId'] as String?,
      id: json['id'] as String?,
      pinCode: json['pinCode'] as String?,
      languageId: json['languageId'] as String?,
      activityId: json['activityId'] as String?,
      serviceId: json['serviceId'] as String?,
      casteId: json['casteId'] as String?,
      community: json['community'] as String?,
      coachingId: json['coachingId'] as String?,
      sqnid: json['sqnid'] as String?,
      cityName: json['cityName'] as String?,
      cityState: json['cityState'] as String?,
      groupId: json['groupId'] as String?,
      language: json['language'] as String?,
      houseId: json['houseId'] as String?,
      tcstatus: json['tcstatus'] as String?,
      tcnumber: json['tcnumber'] as String?,
      staffFirstChild: json['staffFirstChild'] as String?,
      sibling: json['sibling'] as String?,
      siblingDetails: json['siblingDetails'] as String?,
      language1: json['language1'] as String?,
      neetiitca: json['neetiitca'] as String?,
      caste: json['caste'] as String?,
      studentRegNo: json['studentRegNo'] as String?,
      lastResult: json['lastResult'] as String?,
      tcupload: json['tcupload'] as String?,
      emergencyNo: json['emergencyNo'] as String?,
      guardianImage: json['guardianImage'] as String?,
      shortBio: json['shortBio'] as String?,
      uploadStudentImage: json['uploadStudentImage'] as String?,
      isDaycare: json['isDaycare'] as bool?,
      toTime: json['toTime'] as String?,
      fromTime: json['fromTime'] as String?,
      pickupPoint: json['pickupPoint'] as String?,
      transportType: json['transportType'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'addDaycare': addDaycare,
      'studentId': studentId,
      'registrationNo': registrationNo,
      'admissionNo': admissionNo,
      'session': session,
      'studentName': studentName,
      'sex': sex,
      'placeofBirth': placeofBirth,
      'dob': dob,
      'age': age,
      'classId': classId,
      'sectionId': sectionId,
      'religion': religion,
      'nationality': nationality,
      'motherTongue': motherTongue,
      'qnid': qnid,
      'hostel': hostel,
      'aAdharNo': aAdharNo,
      'emisno': emisno,
      'parentStatus': parentStatus,
      'parentId': parentId,
      'fatherName': fatherName,
      'fage': fage,
      'feducation': feducation,
      'foccupation': foccupation,
      'fdesignation': fdesignation,
      'forganisation': forganisation,
      'faddressRes': faddressRes,
      'faddressPerm': faddressPerm,
      'faddressOffice': faddressOffice,
      'fphoneOffice': fphoneOffice,
      'fmobileno': fmobileno,
      'femail': femail,
      'motherName': motherName,
      'mage': mage,
      'meducation': meducation,
      'moccupation': moccupation,
      'mdesignation': mdesignation,
      'morganisation': morganisation,
      'maddressRes': maddressRes,
      'maddressPerm': maddressPerm,
      'maddressOffice': maddressOffice,
      'mphoneoffice': mphoneoffice,
      'mmobileno': mmobileno,
      'memail': memail,
      'smsFather': smsFather,
      'smsMother': smsMother,
      'bloodGroup': bloodGroup,
      'identificationMark': identificationMark,
      'height': height,
      'weight': weight,
      'asthma': asthma,
      'epilepsy': epilepsy,
      'anyOther': anyOther,
      'bcg': bcg,
      'hib': hib,
      'dpt': dpt,
      'influenza': influenza,
      'mmr': mmr,
      'typhoid': typhoid,
      'polio': polio,
      'measles': measles,
      'hepatitisA': hepatitisA,
      'hepatitisB': hepatitisB,
      'chickenpox': chickenpox,
      'dtap': dtap,
      'anyMedicine': anyMedicine,
      'anyFood': anyFood,
      'anythingElse': anythingElse,
      'spectacles': spectacles,
      'blindness': blindness,
      'transportUser': transportUser,
      'routeNo': routeNo,
      'routeNameId': routeNameId,
      'routePointId': routePointId,
      'midDayTo': midDayTo,
      'midDayFrom': midDayFrom,
      'studentPic': studentPic,
      'fatherPic': fatherPic,
      'motherPic': motherPic,
      'aadharPic': aadharPic,
      'birthCertificatePic': birthCertificatePic,
      'action': action,
      'createDate': createDate,
      'promotionDate': promotionDate,
      'promotionStatus': promotionStatus,
      'createBy': createBy,
      'updateBy': updateBy,
      'ppassword': ppassword,
      'rollNo': rollNo,
      'schoolId': schoolId,
      'dateOfAdmission': dateOfAdmission,
      'fqualification': fqualification,
      'mqualification': mqualification,
      'whatsAppNo': whatsAppNo,
      'guardianName': guardianName,
      'guardianPhone': guardianPhone,
      'cityId': cityId,
      'id': id,
      'pinCode': pinCode,
      'languageId': languageId,
      'activityId': activityId,
      'serviceId': serviceId,
      'casteId': casteId,
      'community': community,
      'coachingId': coachingId,
      'sqnid': sqnid,
      'cityName': cityName,
      'cityState': cityState,
      'groupId': groupId,
      'language': language,
      'houseId': houseId,
      'tcstatus': tcstatus,
      'tcnumber': tcnumber,
      'staffFirstChild': staffFirstChild,
      'sibling': sibling,
      'siblingDetails': siblingDetails,
      'language1': language1,
      'neetiitca': neetiitca,
      'caste': caste,
      'studentRegNo': studentRegNo,
      'lastResult': lastResult,
      'tcupload': tcupload,
      'emergencyNo': emergencyNo,
      'guardianImage': guardianImage,
      'shortBio': shortBio,
      'uploadStudentImage': uploadStudentImage,
      'isDaycare': isDaycare,
      'toTime': toTime,
      'fromTime': fromTime,
      'pickupPoint': pickupPoint,
      'transportType': transportType,
    };
  }

  ReportCardInside2Model copyWith({
    String? addDaycare,
    int? studentId,
    String? registrationNo,
    String? admissionNo,
    String? session,
    String? studentName,
    String? sex,
    String? placeofBirth,
    String? dob,
    String? age,
    int? classId,
    int? sectionId,
    String? religion,
    String? nationality,
    String? motherTongue,
    String? qnid,
    String? hostel,
    String? aAdharNo,
    String? emisno,
    String? parentStatus,
    String? parentId,
    String? fatherName,
    String? fage,
    String? feducation,
    String? foccupation,
    String? fdesignation,
    String? forganisation,
    String? faddressRes,
    String? faddressPerm,
    String? faddressOffice,
    String? fphoneOffice,
    String? fmobileno,
    String? femail,
    String? motherName,
    String? mage,
    String? meducation,
    String? moccupation,
    String? mdesignation,
    String? morganisation,
    String? maddressRes,
    String? maddressPerm,
    String? maddressOffice,
    String? mphoneoffice,
    String? mmobileno,
    String? memail,
    String? smsFather,
    String? smsMother,
    String? bloodGroup,
    String? identificationMark,
    String? height,
    String? weight,
    String? asthma,
    String? epilepsy,
    String? anyOther,
    String? bcg,
    String? hib,
    String? dpt,
    String? influenza,
    String? mmr,
    String? typhoid,
    String? polio,
    String? measles,
    String? hepatitisA,
    String? hepatitisB,
    String? chickenpox,
    String? dtap,
    String? anyMedicine,
    String? anyFood,
    String? anythingElse,
    String? spectacles,
    String? blindness,
    String? transportUser,
    String? routeNo,
    String? routeNameId,
    String? routePointId,
    String? midDayTo,
    String? midDayFrom,
    String? studentPic,
    String? fatherPic,
    String? motherPic,
    String? aadharPic,
    String? birthCertificatePic,
    String? action,
    String? createDate,
    String? promotionDate,
    String? promotionStatus,
    String? createBy,
    String? updateBy,
    String? ppassword,
    String? rollNo,
    String? schoolId,
    String? dateOfAdmission,
    String? fqualification,
    String? mqualification,
    String? whatsAppNo,
    String? guardianName,
    String? guardianPhone,
    String? cityId,
    String? id,
    String? pinCode,
    String? languageId,
    String? activityId,
    String? serviceId,
    String? casteId,
    String? community,
    String? coachingId,
    String? sqnid,
    String? cityName,
    String? cityState,
    String? groupId,
    String? language,
    String? houseId,
    String? tcstatus,
    String? tcnumber,
    String? staffFirstChild,
    String? sibling,
    String? siblingDetails,
    String? language1,
    String? neetiitca,
    String? caste,
    String? studentRegNo,
    String? lastResult,
    String? tcupload,
    String? emergencyNo,
    String? guardianImage,
    String? shortBio,
    String? uploadStudentImage,
    bool? isDaycare,
    String? toTime,
    String? fromTime,
    String? pickupPoint,
    String? transportType,
  }) {
    return ReportCardInside2Model(
      addDaycare: addDaycare ?? this.addDaycare,
      studentId: studentId ?? this.studentId,
      registrationNo: registrationNo ?? this.registrationNo,
      admissionNo: admissionNo ?? this.admissionNo,
      session: session ?? this.session,
      studentName: studentName ?? this.studentName,
      sex: sex ?? this.sex,
      placeofBirth: placeofBirth ?? this.placeofBirth,
      dob: dob ?? this.dob,
      age: age ?? this.age,
      classId: classId ?? this.classId,
      sectionId: sectionId ?? this.sectionId,
      religion: religion ?? this.religion,
      nationality: nationality ?? this.nationality,
      motherTongue: motherTongue ?? this.motherTongue,
      qnid: qnid ?? this.qnid,
      hostel: hostel ?? this.hostel,
      aAdharNo: aAdharNo ?? this.aAdharNo,
      emisno: emisno ?? this.emisno,
      parentStatus: parentStatus ?? this.parentStatus,
      parentId: parentId ?? this.parentId,
      fatherName: fatherName ?? this.fatherName,
      fage: fage ?? this.fage,
      feducation: feducation ?? this.feducation,
      foccupation: foccupation ?? this.foccupation,
      fdesignation: fdesignation ?? this.fdesignation,
      forganisation: forganisation ?? this.forganisation,
      faddressRes: faddressRes ?? this.faddressRes,
      faddressPerm: faddressPerm ?? this.faddressPerm,
      faddressOffice: faddressOffice ?? this.faddressOffice,
      fphoneOffice: fphoneOffice ?? this.fphoneOffice,
      fmobileno: fmobileno ?? this.fmobileno,
      femail: femail ?? this.femail,
      motherName: motherName ?? this.motherName,
      mage: mage ?? this.mage,
      meducation: meducation ?? this.meducation,
      moccupation: moccupation ?? this.moccupation,
      mdesignation: mdesignation ?? this.mdesignation,
      morganisation: morganisation ?? this.morganisation,
      maddressRes: maddressRes ?? this.maddressRes,
      maddressPerm: maddressPerm ?? this.maddressPerm,
      maddressOffice: maddressOffice ?? this.maddressOffice,
      mphoneoffice: mphoneoffice ?? this.mphoneoffice,
      mmobileno: mmobileno ?? this.mmobileno,
      memail: memail ?? this.memail,
      smsFather: smsFather ?? this.smsFather,
      smsMother: smsMother ?? this.smsMother,
      bloodGroup: bloodGroup ?? this.bloodGroup,
      identificationMark: identificationMark ?? this.identificationMark,
      height: height ?? this.height,
      weight: weight ?? this.weight,
      asthma: asthma ?? this.asthma,
      epilepsy: epilepsy ?? this.epilepsy,
      anyOther: anyOther ?? this.anyOther,
      bcg: bcg ?? this.bcg,
      hib: hib ?? this.hib,
      dpt: dpt ?? this.dpt,
      influenza: influenza ?? this.influenza,
      mmr: mmr ?? this.mmr,
      typhoid: typhoid ?? this.typhoid,
      polio: polio ?? this.polio,
      measles: measles ?? this.measles,
      hepatitisA: hepatitisA ?? this.hepatitisA,
      hepatitisB: hepatitisB ?? this.hepatitisB,
      chickenpox: chickenpox ?? this.chickenpox,
      dtap: dtap ?? this.dtap,
      anyMedicine: anyMedicine ?? this.anyMedicine,
      anyFood: anyFood ?? this.anyFood,
      anythingElse: anythingElse ?? this.anythingElse,
      spectacles: spectacles ?? this.spectacles,
      blindness: blindness ?? this.blindness,
      transportUser: transportUser ?? this.transportUser,
      routeNo: routeNo ?? this.routeNo,
      routeNameId: routeNameId ?? this.routeNameId,
      routePointId: routePointId ?? this.routePointId,
      midDayTo: midDayTo ?? this.midDayTo,
      midDayFrom: midDayFrom ?? this.midDayFrom,
      studentPic: studentPic ?? this.studentPic,
      fatherPic: fatherPic ?? this.fatherPic,
      motherPic: motherPic ?? this.motherPic,
      aadharPic: aadharPic ?? this.aadharPic,
      birthCertificatePic: birthCertificatePic ?? this.birthCertificatePic,
      action: action ?? this.action,
      createDate: createDate ?? this.createDate,
      promotionDate: promotionDate ?? this.promotionDate,
      promotionStatus: promotionStatus ?? this.promotionStatus,
      createBy: createBy ?? this.createBy,
      updateBy: updateBy ?? this.updateBy,
      ppassword: ppassword ?? this.ppassword,
      rollNo: rollNo ?? this.rollNo,
      schoolId: schoolId ?? this.schoolId,
      dateOfAdmission: dateOfAdmission ?? this.dateOfAdmission,
      fqualification: fqualification ?? this.fqualification,
      mqualification: mqualification ?? this.mqualification,
      whatsAppNo: whatsAppNo ?? this.whatsAppNo,
      guardianName: guardianName ?? this.guardianName,
      guardianPhone: guardianPhone ?? this.guardianPhone,
      cityId: cityId ?? this.cityId,
      id: id ?? this.id,
      pinCode: pinCode ?? this.pinCode,
      languageId: languageId ?? this.languageId,
      activityId: activityId ?? this.activityId,
      serviceId: serviceId ?? this.serviceId,
      casteId: casteId ?? this.casteId,
      community: community ?? this.community,
      coachingId: coachingId ?? this.coachingId,
      sqnid: sqnid ?? this.sqnid,
      cityName: cityName ?? this.cityName,
      cityState: cityState ?? this.cityState,
      groupId: groupId ?? this.groupId,
      language: language ?? this.language,
      houseId: houseId ?? this.houseId,
      tcstatus: tcstatus ?? this.tcstatus,
      tcnumber: tcnumber ?? this.tcnumber,
      staffFirstChild: staffFirstChild ?? this.staffFirstChild,
      sibling: sibling ?? this.sibling,
      siblingDetails: siblingDetails ?? this.siblingDetails,
      language1: language1 ?? this.language1,
      neetiitca: neetiitca ?? this.neetiitca,
      caste: caste ?? this.caste,
      studentRegNo: studentRegNo ?? this.studentRegNo,
      lastResult: lastResult ?? this.lastResult,
      tcupload: tcupload ?? this.tcupload,
      emergencyNo: emergencyNo ?? this.emergencyNo,
      guardianImage: guardianImage ?? this.guardianImage,
      shortBio: shortBio ?? this.shortBio,
      uploadStudentImage: uploadStudentImage ?? this.uploadStudentImage,
      isDaycare: isDaycare ?? this.isDaycare,
      toTime: toTime ?? this.toTime,
      fromTime: fromTime ?? this.fromTime,
      pickupPoint: pickupPoint ?? this.pickupPoint,
      transportType: transportType ?? this.transportType,
    );
  }

  @override
  String toString() {
    return 'ReportCardInside2Model(studentId: $studentId, studentName: $studentName, '
        'registrationNo: $registrationNo, session: $session, schoolId: $schoolId)';
  }
}